/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


typedef volatile unsigned int vuint32_t ;
#include <stdint.h>

// =============== register address ===============

// RCC
#define RCC_BASE        0x40021000
#define RCC_APB2ENR     *(volatile uint32_t *)(RCC_BASE  + 0x18)
#define RCC_IOPAEN      (1<<2)
#define RCC_AFIOEN      (1<<0)

// GPIO
#define GPIOA_BASE      0x40010800
#define GPIOA_CRL       *(volatile uint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH       *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR       *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define GPIOA13         (1UL<<13)

// EXTI
#define EXTI_BASE       0x40010400
#define EXTI_IMR        *(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RSTR       *(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR         *(volatile uint32_t *)(EXTI_BASE + 0x14)

// AFIO
#define AFIO_BASE       0x40010000
#define AFIO_EXTICR1    *(volatile uint32_t *)(AFIO_BASE + 0x08)

// NVIC (we got it from ARM Website)
#define NVIC_EXTIE0     *(volatile uint32_t *)(0xE000E100 + 0x00)



// =============== Init functions ===============
void clock_Init(){
	// I/O port A clock enable
	RCC_APB2ENR |= RCC_IOPAEN;

	// Alternate function I/O clock enable
	RCC_APB2ENR |= RCC_AFIOEN;
}


void gpio_Init(){
	// PORTA 13 Output
	GPIOA_CRH    &= 0xff0fffff;
	GPIOA_CRH    |= 0x00200000;

	// PORTA 0 Input floating
	GPIOA_CRL |= (1<<2);
}

void nvic_Init(){
	// Enable NVIC IRQ6 (EXTI0)
	NVIC_EXTIE0 |= (1<<6);
}

void exti_Init(){
	// EXTI0 >> PORTA 0
	AFIO_EXTICR1 =0;

	// Rising trigger
	EXTI_RSTR |= (1<<0);

	// Enable EXTI line 0
	EXTI_IMR |= (1<<0);

}

int main(void)
{
	// HW initialization
	clock_Init();
	gpio_Init();
	nvic_Init();
	exti_Init();



	while(1){

	}

	return 0;
}

// ISR for EXTI0 (Rising edge for PORTA 0)
void EXTI0_IRQHandler(){
	// toggle led at PORTA 13
	GPIOA_ODR ^= (1<<13);

	// clear pending request for line 0
	EXTI_PR |= (1<<0);
}
